name: CI Pipeline

on: 
  push: 
    branches:
    - main

permissions:
  contents: read
  packages: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      #backend test
      - name: Setup node (backend)
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install backend dependencies
        run: |
            cd backend
            npm install

      - name: Run backend tests
        run: |
            cd backend
            npm test

      #frontend test
      - name: Install frontend dependencies
        run: |
            cd frontend
            npm ci
      
      - name: Run frontend tests
        run: |
            cd frontend
            npm test -- --run
  

  build-and-push:
    needs: tests
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - name: Set lowercase repository owner
        run: |
          echo "OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push backend
        run: |
            docker build -t ghcr.io/${OWNER}/cid-meme-backend:latest ./backend
            docker push ghcr.io/${OWNER}/cid-meme-backend:latest
        
      - name: Build and Push frontend
        run: |
            docker build \
              --build-arg VITE_API_URL=http://${{ secrets.EC2_HOST }}:5000 \
              -t ghcr.io/${OWNER}/cid-meme-frontend:latest ./frontend

            docker push ghcr.io/${OWNER}/cid-meme-frontend:latest


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd app
            docker compose pull
            docker compose down
            docker compose up -d





      